version: '2'
services:
    jhipster-mysql:
<<<<<<< HEAD
        image: mysql:5.7.18
=======
        image: mysql:5.7.13
>>>>>>> 3889c913b8266976ebe9e376a2fe1ef96ea458d8
        # volumes:
        #     - ~/volumes/jhipster/jhipster/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipster
        ports:
            - 3306:3306
<<<<<<< HEAD
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
=======
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
>>>>>>> 3889c913b8266976ebe9e376a2fe1ef96ea458d8
